FROM python:3.7-alpine

RUN apk add --no-cache g++ snappy-dev

COPY requirements.celery.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./api /api
WORKDIR /api

ENTRYPOINT celery -A celery_worker.worker worker -E -P celery_pool_asyncio:TaskPool