FROM python:3.7

RUN apt-get update && apt-get install libsnappy-dev -y

COPY requirements.celery.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./api /api
WORKDIR /api

ENTRYPOINT sleep 10 && celery -A celery_worker.worker beat --scheduler celery_pool_asyncio:PersistentScheduler