FROM python:3.7

COPY requirements.celery.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./api /api
WORKDIR /api

ENTRYPOINT sleep 10 && celery -A celery_worker.worker worker -E -P celery_pool_asyncio:TaskPool