FROM python:3.7

COPY requirements.celery.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./api /api
WORKDIR /api

ENTRYPOINT celery -A celery_worker.worker beat -l INFO --scheduler celery_pool_asyncio:PersistentScheduler